import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BriefcaseBusiness, Building2, Handshake, Lightbulb, Network, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CTA, DevelopmentModel, ImpactMetrics, Pathway, ProgrammeGrid, SectionHeading } from "@/components/site/sections";
import hero from "@/assets/asihwebe-hero.jpg";
import entrepreneur from "@/assets/entrepreneur-digital.jpg";
import workshop from "@/assets/skills-workshop.jpg";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Asihwebe Foundation | Enterprise & Community Development South Africa"},{name:"description",content:"Asihwebe Foundation creates practical pathways for South African entrepreneurs and communities through enterprise development, digital enablement, skills and partnerships."},{property:"og:title",content:"Asihwebe Foundation | Enabling Opportunity"},{property:"og:description",content:"Enterprise development, digital enablement, skills development and community activation in South Africa."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}]}),component:Home});

function Home(){return <>
  <section className="relative min-h-[calc(92svh-5rem)] overflow-hidden bg-brand-navy"><img src={hero} alt="South African entrepreneurs collaborating in a community business workshop" width={1920} height={1088} className="absolute inset-0 h-full w-full object-cover object-center" fetchPriority="high"/><div className="hero-overlay absolute inset-0"/><div className="site-container relative flex min-h-[calc(92svh-5rem)] items-center py-16"><div className="max-w-3xl"><p className="eyebrow text-brand-gold">Asihwebe Foundation · South Africa</p><h1 className="mt-5 text-balance font-display text-4xl font-bold leading-[1.08] text-primary-foreground sm:text-5xl lg:text-7xl">Empowering Communities. Enabling Opportunity. Shaping Futures.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-primary-foreground/80 md:text-lg">Asihwebe Foundation works with communities, entrepreneurs and strategic partners to unlock opportunity through enterprise development, digital enablement, skills development and practical community programmes.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild variant="gold" size="lg"><Link to="/programmes">Explore Our Programmes<ArrowRight/></Link></Button><Button asChild variant="heroOutline" size="lg"><Link to="/partnerships">Partner With Us</Link></Button></div></div></div></section>
  <section className="section-pad"><div className="site-container grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><SectionHeading eyebrow="Who we are" title="Building Pathways to Opportunity" copy="Asihwebe Foundation is a South African non-profit organisation committed to strengthening communities and expanding access to economic opportunity."/><p className="mt-5 leading-7 text-muted-foreground">We focus on practical interventions that help entrepreneurs and communities build capability, embrace digital tools, access markets and connect with organisations that can support sustainable growth.</p><p className="mt-4 leading-7 text-muted-foreground">Our work brings together community activation, enterprise development, digital enablement and strategic partnerships to turn opportunity into practical action.</p><Button asChild variant="navy" className="mt-7"><Link to="/about">Discover Our Story<ArrowRight/></Link></Button></div><img src={entrepreneur} alt="South African small business owner using digital tools for her enterprise" width={1408} height={1008} loading="lazy" className="aspect-[4/3] w-full object-cover"/></div></section>
  <section className="section-pad bg-muted"><div className="site-container"><SectionHeading eyebrow="Our approach" title="Connect. Enable. Activate. Grow." copy="A connected development journey that brings people, capability and partnerships together to create practical economic opportunity."/><DevelopmentModel/></div></section>
  <section className="section-pad"><div className="site-container"><SectionHeading eyebrow="Impact areas" title="Four areas of practical development" copy="Our impact areas define where we focus. Specific programmes translate this work into structured delivery."/><ProgrammeGrid/></div></section>
  <section className="section-pad bg-brand-navy"><div className="site-container"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-end"><SectionHeading light eyebrow="Flagship programme · TRDEA" title="Township & Rural Digital Enterprise Accelerator" copy="A practical enterprise-development programme designed to help township and rural entrepreneurs become more digitally enabled, market-ready and connected to economic opportunity."/><div className="flex flex-wrap gap-3 lg:justify-end"><Button asChild variant="gold"><Link to="/trdea">Explore TRDEA<ArrowRight/></Link></Button><Button asChild variant="heroOutline"><Link to="/partnerships">Partner With TRDEA</Link></Button></div></div><Pathway/></div></section>
  <section className="section-pad"><div className="site-container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><img src={workshop} alt="Young South African entrepreneurs taking part in a practical skills workshop" width={1408} height={1008} loading="lazy" className="aspect-[4/3] w-full object-cover"/><div><SectionHeading eyebrow="For institutional partners" title="For Organisations Looking to Create Meaningful Impact" copy="Whether you are looking to support entrepreneurs, strengthen communities, advance digital inclusion, develop skills or create access to economic opportunity, Asihwebe provides a platform for collaborative programme delivery."/><div className="mt-7 grid gap-3 sm:grid-cols-2">{[{Icon:Building2,label:"Sponsor a Programme"},{Icon:Handshake,label:"Partner With Us"},{Icon:Users,label:"Support a Cohort"},{Icon:Lightbulb,label:"Provide Expertise"}].map(({Icon,label})=><div key={label} className="flex items-center gap-3 border-b pb-3 text-sm font-semibold text-brand-navy"><Icon className="size-5 text-brand-orange"/>{label}</div>)}</div><Button asChild variant="navy" className="mt-7"><Link to="/partnerships">Explore Partnership Pathways<ArrowRight/></Link></Button></div></div></section>
  <section className="section-pad bg-brand-navy"><div className="site-container"><SectionHeading light eyebrow="Impact" title="Accountable from the start" copy="Our impact dashboard is ready for verified programme information. Figures will only be published after validation."/><ImpactMetrics/></div></section>
  <section className="section-pad bg-muted"><div className="site-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Support our work" title="Support Opportunity. Strengthen Communities." copy="Support can take the form of sponsorship, expertise, technology, market access, partnership or community mobilisation."/><div className="grid gap-px bg-border sm:grid-cols-2">{[[BriefcaseBusiness,"Programme sponsorship"],[Users,"Entrepreneur cohort support"],[Network,"Market and technology access"],[Handshake,"Strategic partnerships"]].map(([Icon,label])=>{const ItemIcon=Icon as typeof BriefcaseBusiness;return <div key={String(label)} className="flex items-center gap-4 bg-background p-6"><ItemIcon className="text-brand-orange"/><p className="font-semibold text-brand-navy">{String(label)}</p></div>})}<Button asChild variant="gold" size="lg" className="sm:col-span-2"><Link to="/support">Explore Ways to Support<ArrowRight/></Link></Button></div></div></section>
  <CTA title="Let’s build opportunity together" copy="Start a practical conversation about community activation, entrepreneur development or collaborative programme delivery."/>
</>}