import { Link, useRouterState } from "@tanstack/react-router";
import { ChevronDown, Linkedin, Mail, MapPin, Menu, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Brand } from "./brand";

const nav = [["Home", "/"], ["About Us", "/about"], ["Programmes", "/programmes"], ["Partnerships", "/partnerships"], ["Impact", "/impact"], ["Contact", "/contact"]] as const;
const programmeLinks = ["Enterprise Development", "Digital Enablement", "Skills & Capacity Development", "Community Activation"];

export function SiteHeader() {
  const [open,setOpen]=useState(false); const pathname=useRouterState({select:s=>s.location.pathname});
  return <header className="sticky top-0 z-50 border-b border-brand-navy/10 bg-background/95 backdrop-blur"><div className="site-container flex min-h-20 items-center justify-between gap-5 py-2"><Brand/><nav className="hidden items-center gap-0.5 lg:flex" aria-label="Primary navigation">{nav.map(([label,to])=>label==="Programmes"?<div key={to} className="group relative"><Link to={to} className={`nav-link inline-flex items-center gap-1 ${pathname===to||pathname==="/trdea"?"nav-link-active":""}`}>{label}<ChevronDown className="size-3.5"/></Link><div className="invisible absolute left-0 top-full w-72 border border-border bg-background p-2 opacity-0 shadow-lg transition group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><Link to="/programmes" className="block border-b px-3 py-2 text-sm font-bold text-brand-navy">All impact areas</Link>{programmeLinks.map(item=><Link key={item} to="/programmes" className="block px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-brand-navy">{item}</Link>)}<Link to="/trdea" className="block border-t px-3 py-2 text-sm font-bold text-brand-orange">TRDEA flagship programme</Link></div></div>:<Link key={to} to={to} className={`nav-link ${pathname===to?"nav-link-active":""}`}>{label}</Link>)}</nav><div className="hidden lg:block"><Button asChild variant="gold"><Link to="/partnerships">Partner With Us</Link></Button></div><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?"Close menu":"Open menu"}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="border-t bg-background px-5 py-5 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto flex max-w-xl flex-col gap-1">{nav.map(([label,to])=><div key={to}><Link to={to} onClick={()=>setOpen(false)} className="block rounded-sm px-3 py-3 font-semibold text-brand-navy hover:bg-muted">{label}</Link>{label==="Programmes"&&<Link to="/trdea" onClick={()=>setOpen(false)} className="ml-5 block border-l border-brand-gold px-3 py-2 text-sm font-semibold text-brand-orange">TRDEA flagship programme</Link>}</div>)}<Button asChild variant="gold" className="mt-3"><Link to="/partnerships" onClick={()=>setOpen(false)}>Partner With Us</Link></Button></div></nav>}</header>;
}

export function SiteFooter(){const links=[["Home","/"],["About Us","/about"],["Programmes","/programmes"],["TRDEA","/trdea"],["Partnerships","/partnerships"],["Impact","/impact"],["Contact","/contact"],["Support Our Work","/support"]] as const;return <footer className="bg-brand-navy text-primary-foreground"><div className="site-container grid gap-10 py-14 md:grid-cols-[1.4fr_1fr_1fr]"><div><Brand inverse/><p className="mt-5 max-w-sm text-sm leading-6 text-primary-foreground/70">Connecting communities, enabling participation and activating practical pathways to growth.</p></div><div><h2 className="footer-heading">Navigate</h2><div className="grid grid-cols-2 gap-x-6 gap-y-3">{links.map(([label,to])=><Link key={to} to={to} className="text-sm text-primary-foreground/70 hover:text-brand-gold">{label}</Link>)}</div></div><div><h2 className="footer-heading">Contact</h2><p className="footer-line"><MapPin/>South Africa</p><a className="footer-line hover:text-brand-gold" href="mailto:info@asihwebe.org.za"><Mail/>info@asihwebe.org.za</a><span className="footer-line"><Linkedin/>LinkedIn profile to be added</span></div></div><div className="border-t border-primary-foreground/15"><div className="site-container flex flex-col gap-3 py-5 text-xs text-primary-foreground/60 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 Asihwebe Foundation. All rights reserved.</p><div className="flex gap-5"><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Website Terms</Link></div></div></div></footer>}
