import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, Handshake, Network, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { programmes, pathway } from "@/lib/site-content";

export function Eyebrow({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <p className={`eyebrow ${light ? "text-brand-gold" : "text-brand-orange"}`}>{children}</p>; }
export function PageHero({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <section className="page-hero"><div className="site-container py-20 md:py-28"><Eyebrow light>{eyebrow}</Eyebrow><h1 className="mt-4 max-w-4xl text-balance font-display text-4xl font-bold leading-tight text-primary-foreground md:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/75">{copy}</p></div></section>; }
export function SectionHeading({ eyebrow, title, copy, light = false }: { eyebrow: string; title: string; copy?: string; light?: boolean }) { return <div className="max-w-3xl"><Eyebrow light={light}>{eyebrow}</Eyebrow><h2 className={`mt-3 text-balance font-display text-3xl font-bold leading-tight md:text-5xl ${light ? "text-primary-foreground" : "text-brand-navy"}`}>{title}</h2>{copy && <p className={`mt-5 text-base leading-7 md:text-lg ${light ? "text-primary-foreground/70" : "text-muted-foreground"}`}>{copy}</p>}</div>; }
export function ProgrammeGrid() { return <div className="mt-12 grid gap-px overflow-hidden rounded-md border bg-border md:grid-cols-2">{programmes.map(({title,description,icon:Icon}, i) => <article key={title} className="group bg-background p-7 md:p-9"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-sm bg-brand-gold-soft text-brand-orange"><Icon /></span><span className="text-xs font-bold text-muted-foreground">0{i+1}</span></div><h3 className="mt-7 font-display text-xl font-bold text-brand-navy">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{description}</p><Link to="/programmes" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-brand-orange">Learn more <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></Link></article>)}</div>; }
export function Pathway() { return <ol className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{pathway.map((step, i) => <li key={step} className="relative border-l-2 border-brand-gold bg-primary-foreground/5 p-5"><span className="text-xs font-bold text-brand-gold">{String(i+1).padStart(2,"0")}</span><p className="mt-2 font-semibold text-primary-foreground">{step}</p></li>)}</ol>; }
export function ImpactMetrics() { return <div className="mt-10 grid gap-px overflow-hidden rounded-md bg-primary-foreground/15 sm:grid-cols-2 lg:grid-cols-4">{["Entrepreneurs Reached","Communities Engaged","Training Days Delivered","Digital Businesses Enabled"].map(label => <div key={label} className="bg-brand-navy-light p-7"><p className="font-display text-4xl font-bold text-brand-gold">—</p><p className="mt-3 text-sm font-semibold text-primary-foreground">{label}</p><p className="mt-1 text-xs text-primary-foreground/55">Verified figure to be added</p></div>)}</div>; }
export function CTA({ title, copy, primary = "Partner With Us", to = "/contact" }: { title: string; copy: string; primary?: string; to?: "/contact" | "/support" | "/programmes" | "/trdea" }) { return <section className="bg-brand-gold"><div className="site-container flex flex-col gap-7 py-12 md:flex-row md:items-center md:justify-between"><div className="max-w-2xl"><h2 className="font-display text-3xl font-bold text-brand-navy">{title}</h2><p className="mt-3 leading-7 text-brand-navy/75">{copy}</p></div><Button asChild variant="navy" size="lg"><Link to={to}>{primary}<ArrowRight /></Link></Button></div></section>; }
export function ValuesStrip() { const items=[["Connect",Network],["Enable",Sparkles],["Activate",Handshake],["Grow",Check]] as const; return <div className="mt-12 grid gap-6 md:grid-cols-4">{items.map(([name,Icon], i)=><div key={name} className="border-t-2 border-brand-gold pt-5"><Icon className="text-brand-orange"/><p className="mt-4 text-xs font-bold text-muted-foreground">0{i+1}</p><h3 className="mt-1 font-display text-xl font-bold text-brand-navy">{name}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{name === "Connect" ? "Linking people with institutions, markets, resources and opportunity." : name === "Enable" ? "Providing practical digital tools, business capability and skills." : name === "Activate" ? "Turning programmes and partnerships into community-level action." : "Supporting sustainable participation and economic growth."}</p></div>)}</div>; }
