/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrdeaRouteImport } from './routes/trdea'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrdeaRoute = TrdeaRouteImport.update({
  id: '/trdea',
  path: '/trdea',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trdea': typeof TrdeaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trdea': typeof TrdeaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/partnerships': typeof PartnershipsRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trdea': typeof TrdeaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/partnerships'
    | '/privacy'
    | '/programmes'
    | '/support'
    | '/terms'
    | '/trdea'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/partnerships'
    | '/privacy'
    | '/programmes'
    | '/support'
    | '/terms'
    | '/trdea'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/impact'
    | '/partnerships'
    | '/privacy'
    | '/programmes'
    | '/support'
    | '/terms'
    | '/trdea'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgrammesRoute: typeof ProgrammesRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TrdeaRoute: typeof TrdeaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trdea': {
      id: '/trdea'
      path: '/trdea'
      fullPath: '/trdea'
      preLoaderRoute: typeof TrdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  PartnershipsRoute: PartnershipsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgrammesRoute: ProgrammesRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TrdeaRoute: TrdeaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
